# 使用官方 ASP.NET Core 9.0 運行時映像作為基礎映像
FROM mcr.microsoft.com/dotnet/asp.net:9.0 AS base 
WORKDIR /app
# Http 端口
EXPOSE 80
# Https 端口
EXPOSE 443

# 使用官方 ASP.NET Core 9.0 SDK 映像作為構建映像
FROM mcr.microsoft.com/dotnet/sdk:9.0 as build
WORKDIR /src
# 複製當前目錄內容到工作目錄只複製了 .csproj 檔案，以便先執行 dotnet restore（優化建置速度）
COPY ["Project01_movie_lease_system.csproj", "."]
RUN dotnet restore "./Project01_movie_lease_system.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Project01_movie_lease_system.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Project01_movie_lease_system.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Project01_movie_lease_system.dll"]